#!/bin/sh

ENABLED=yes
PROCS=vlmcsd
ARGS="-i /opt/etc/vlmcsd.ini"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
